### ISSUE TITLE
Cannot find module 'eslint-plugin-cypress'

### ISSUE THREAD

**Issue by mrchief** [iannbing/eslint-config-react-airbnb-prettier#1] opened 2018-11-16 04:07 UTC
Version
```
"eslint-config-react-airbnb-prettier": "^0.0.6",
```

config
```
{
  "extends": ["react-airbnb-prettier"]
}
```

I get this error in VSCode:

```
[Error - 11:05:52 PM] Failed to load plugin cypress: Cannot find module 'eslint-plugin-cypress'
```

**Comment by iannbing** [comment] 2018-11-18 23:18
Hi, I cannot reproduce the issue. It's very unlikely be the issue of this package since `eslint-plugin-cypress` is part of the dependencies. Could you check if you also have `eslintConfig` in your `package.json`?

**Comment by mrchief** [comment] 2018-11-19 02:18
I don't have `eslintConfig` in `package.json`. For some reason, cypress plugin doesn't get installed I guess. I'm on Windows.

**Comment by iannbing** [comment] 2018-11-19 12:39
Thanks for reporting. I can also reproduce this issue on Mac. It seems like an issue of `babel-eslint` to `^10.0.1` this issue can be resolved. Please upgrade to version `0.0.9`. I'll close this issue for now. Feel free to re-open this issue if it still persists.

**Closed by iannbing** 2018-11-19 12:39 UTC
